### Imports

In [2]:
import nltk

In [1]:
import numpy as np
from nltk.tokenize import word_tokenize, sent_tokenize

### Tokenize Dataset

In [1]:
file = open('Corpus')
Corpus = file.read()

# Sentence Tokenize
Corpus = sent_tokenize(Corpus)

# Word Tokenize
split_Corpus = []
for sentence in Corpus:
    sentence = word_tokenize(sentence)
    split_Corpus.append(sentence)
    #print(sentence)
    #print("\n")
    


NameError: name 'sent_tokenize' is not defined

### Indexing Lists

In [3]:

listl = ['this','is','a','test']
n = 2
seg = []
for i in range(len(listl)-n+1):
    seg = listl[i:i+n]
    print(seg)
    

    



['this', 'is']
['is', 'a']
['a', 'test']


### Making A Vocabulary

In [4]:
vocab = []
for sentence in split_Corpus:
    for word in sentence:
        if word not in vocab:
            vocab.append(word)
print(vocab[:500])

['The', 'Files', 'of', 'Marcus', 'Nepos', 'Martius', ',', '710', 'AUC', '(', '44', 'BC', ')', 'Part', 'I', 'Rome', 'Italia', 'Roman', 'Republic', 'Chapter', 'Caesar', 'was', 'dead', '.', 'sprinted', 'headlong', 'down', 'the', 'hill', 'my', 'heart', 'thumping', 'legs', 'pumping', 'wind', 'blowing', 'against', 'face', 'hard', 'enough', '–', 'given', 'how', 'fast', 'going', 'to', 'almost', 'choke', 'me', 'cool', 'night', 'air', 'spiraled', 'around', 'as', 'tried', 'pick', 'up', 'pace', ';', 'breath', 'quickened', 'but', 'pushed', 'on', 'figure', 'a', 'dark', 'shadow', 'in', 'moonless', 'still', 'ahead', 'fight', 'for', 'power', 'had', 'begun', 'My', 'mind', 'expert', 'such', 'matters', 'already', 'raced', 'through', 'possibilities', 'what', 'headed', 'into', 'capacity', 'general', 'that', 'certain', 'keep', 'pursuit', 'Few', 'people', 'knew', 'could', 'do', 'sprinting', 'Palatine', 'city', 'Eternal', 'City', 'himself', 'It', 'long', 'past', 'midnight', 'now', 'lamps', 'illuminated', 'insi

### Word to Integer

In [5]:
def word_to_integer(vocab, word):
    if word in vocab:
        integer = vocab.index(word) + 1
    else:
        integer = 0
        
    return integer
        
# Test

print(word_to_integer(vocab, 'was'))
print(word_to_integer(vocab, 'asfqwdgdfsf'))

22
0


In [6]:
def integer_to_word(vocab, integer):
    if 0 < integer < len(vocab):
        word = vocab[integer-1]   
    elif integer == 0:
        word = '<unk>'   
    elif integer >= len(vocab):
        word = None
        print("Index is too high")
    
    return word

# Test

print(integer_to_word(vocab, 22))
print(integer_to_word(vocab, 0))
print(integer_to_word(vocab, 1000000000))

        

was
<unk>
Index is too high
None


### Changing the Corpus from Words to Numbers

In [7]:
tokenized_Corpus = []

for sentence in split_Corpus:
    sent = []
    for word in sentence:
        sent.append(word_to_integer(vocab, word))
    
    tokenized_Corpus.append(sent)
    
# Test

print(tokenized_Corpus[:500])

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 7, 17, 7, 18, 19, 20, 15, 21, 22, 23, 24], [15, 25, 26, 27, 28, 29, 7, 30, 31, 32, 7, 30, 33, 34, 7, 28, 35, 36, 37, 28, 38, 39, 40, 41, 42, 43, 44, 15, 22, 45, 41, 46, 47, 48, 49, 24], [1, 50, 51, 52, 53, 54, 49, 55, 15, 56, 46, 57, 58, 59, 60, 30, 61, 62, 7, 63, 15, 64, 65, 24], [1, 66, 7, 67, 68, 69, 70, 28, 71, 51, 7, 22, 72, 73, 24], [1, 74, 75, 76, 77, 78, 24], [79, 80, 7, 81, 70, 82, 83, 7, 77, 84, 85, 86, 28, 87, 3, 88, 15, 22, 89, 90, 60, 82, 22, 28, 91, 3, 67, 92, 24], [1, 66, 22, 44, 7, 93, 22, 94, 41, 44, 40, 46, 95, 73, 3, 49, 55, 15, 25, 70, 96, 24], [97, 98, 7, 15, 99, 7, 100, 101, 93, 24], [1, 29, 15, 22, 102, 27, 22, 28, 103, 7, 28, 104, 54, 49, 28, 105, 106, 107, 24], [108, 22, 109, 110, 111, 112, 7, 63, 28, 113, 93, 114, 28, 115, 3, 116, 117, 118, 119, 120, 121, 28, 122, 3, 28, 51, 24], [123, 28, 66, 99, 43, 46, 95, 46, 28, 124, 41, 125, 28, 113, 7, 126, 93, 127, 15, 100, 128, 129, 130, 131, 132, 28, 133, 117, 

### Integer to One-Hot Vector

In [8]:
def int_to_vec(integer, vocab_len):
    l = [0 for i in range(vocab_len+1)]
    l[integer] = 1
    vector = np.asarray(l)
    vector = vector.reshape(-1, 1)
    return vector

# Test

vec = int_to_vec(1, 7)
print(vec)
print(vec.shape)

[[0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
(8, 1)


### Creating Windows

In [9]:
def create_windows(window_size, corpus):
    windows = []
    for sentence in corpus:
        for i in range(window_size, len(sentence)-window_size):
            window = sentence[i-window_size:i+window_size+1]
            windows.append(window)
    return windows
            
windows = create_windows(2, tokenized_Corpus)

# Test

#print(windows[:100])

# Or

for window in windows[:50]:
    words = []
    for integer in window:
        word = integer_to_word(vocab, integer)
        words.append(word)
        
    print(words)
    #print(len(words))
    
        
    

['The', 'Files', 'of', 'Marcus', 'Nepos']
['Files', 'of', 'Marcus', 'Nepos', 'Martius']
['of', 'Marcus', 'Nepos', 'Martius', ',']
['Marcus', 'Nepos', 'Martius', ',', '710']
['Nepos', 'Martius', ',', '710', 'AUC']
['Martius', ',', '710', 'AUC', '(']
[',', '710', 'AUC', '(', '44']
['710', 'AUC', '(', '44', 'BC']
['AUC', '(', '44', 'BC', ')']
['(', '44', 'BC', ')', 'Part']
['44', 'BC', ')', 'Part', 'I']
['BC', ')', 'Part', 'I', 'Rome']
[')', 'Part', 'I', 'Rome', ',']
['Part', 'I', 'Rome', ',', 'Italia']
['I', 'Rome', ',', 'Italia', ',']
['Rome', ',', 'Italia', ',', 'Roman']
[',', 'Italia', ',', 'Roman', 'Republic']
['Italia', ',', 'Roman', 'Republic', 'Chapter']
[',', 'Roman', 'Republic', 'Chapter', 'I']
['Roman', 'Republic', 'Chapter', 'I', 'Caesar']
['Republic', 'Chapter', 'I', 'Caesar', 'was']
['Chapter', 'I', 'Caesar', 'was', 'dead']
['I', 'Caesar', 'was', 'dead', '.']
['I', 'sprinted', 'headlong', 'down', 'the']
['sprinted', 'headlong', 'down', 'the', 'hill']
['headlong', 'down', 'th

### Adding Lists Practice

In [10]:
list1 = ['Hello','my']
list2 = ['name', 'is']

print(list1 + list2)

['Hello', 'my', 'name', 'is']


### Generating Context and Target Vectors

In [11]:
def generate_context_target(window, window_size, vocab_len):
    target_word = window[window_size]
    context_words = window[:window_size] + window[window_size+1:]
    
    target_vector = int_to_vec(target_word, vocab_len)
    context_vectors = []
    for word in context_words:
        context_vectors.append(int_to_vec(word, vocab_len))
    
    return target_vector, context_vectors
    # NOTE: context_vectors is a list of vectors

# Test

window = ["Hi", "my", "name", "is", "Valensus"]
window = [word_to_integer(vocab, word) for word in window]
window_size = 2

target_vector_test, context_vectors_test = generate_context_target(window, window_size, len(vocab))
print(target_vector_test, '\n\n', context_vectors_test)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]] 

 [array([[1],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]]), array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]]), array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]]), array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])]


### Averaging Context Vectors

In [12]:
def average_context_vectors(context_vectors):
    context_vectors_added = sum(context_vectors)
    context_vectors_average = context_vectors_added /len(context_vectors)
    
    return context_vectors_average

# Test

print(average_context_vectors(context_vectors_test))


[[0.25]
 [0.  ]
 [0.  ]
 ...
 [0.  ]
 [0.  ]
 [0.  ]]


### Initialize Model

In [13]:
def initialize_model(embedding_length, vocab_length):
    W1 = np.random.rand(embedding_length, vocab_length+1)
    W2 = np.random.rand(vocab_length+1, embedding_length)
    b1 = np.random.rand(embedding_length, 1)
    b2 = np.random.rand(vocab_length+1, 1)
    
    return W1, W2, b1, b2
    

### Forward Propagation

In [14]:
def forward_prop(x, W1, W2, b1, b2):
    
    z1 = np.dot(W1, x) + b1
    z1 = np.maximum(0,z1)
    z2 = np.dot(W2, z1) + b2
    # Softmax
    e_z = np.exp(z2)
    yhat = e_z/np.sum(e_z,axis=0)
    
    return yhat, z2, z1

### Cost Function

In [15]:
def compute_cost(y, yhat, batch_size):
    # cost function 
    logprobs = np.multiply(np.log(yhat),y) + np.multiply(np.log(1 - yhat), 1 - y)
    cost = - 1/batch_size * np.sum(logprobs)
    cost = np.squeeze(cost)
    return cost

### Backpropagation

In [16]:
def back_prop(x, yhat, y, z1, W1, W2, b1, b2, batch_size):
    
    l1 = np.dot(W2.T,(yhat-y))

    l1 = np.maximum(0,l1)

    grad_W1 = (1/batch_size)*np.dot(l1,x.T) 

    grad_W2 = (1/batch_size)*np.dot(yhat-y,z1.T)

    grad_b1 = np.sum((1/batch_size)*np.dot(l1,x.T),axis=1,keepdims=True)

    grad_b2 = np.sum((1/batch_size)*np.dot(yhat-y,z1.T),axis=1,keepdims=True)
    
    return grad_W1, grad_W2, grad_b1, grad_b2

    

### Updating Weights and Biases

In [17]:
def update_parameters(W1, W2, b1, b2, grad_W1, grad_W2, grad_b1, grad_b2, alpha):
    
    W1 -= alpha*grad_W1 
    W2 -= alpha*grad_W2
    b1 -= alpha*grad_b1
    b2 -= alpha*grad_b2
    
    return W1, W2, b1, b2
    
    

### Creating Batches 

In [18]:
def create_batches(inputs, batch_size):
    
    batches = []
    stop = len(inputs)//batch_size+2
    index = 0
    for i in range(1, stop):
        batch = inputs[index:index+batch_size]
        index += batch_size
        batches.append(batch)
    
    return batches

Batches = create_batches(windows, 64)
for i in range(1):
    print(Batches[1532:])
    print(len(Batches[i]))
    print(len(Batches))
    print(len(windows)//64+1)
    
    

[[[2638, 1784, 7, 763, 28], [1784, 7, 763, 28, 3816], [7, 763, 28, 3816, 3], [763, 28, 3816, 3, 28], [28, 3816, 3, 28, 594], [3816, 3, 28, 594, 595], [3, 28, 594, 595, 7], [28, 594, 595, 7, 118], [594, 595, 7, 118, 8992], [595, 7, 118, 8992, 7], [7, 118, 8992, 7, 763], [118, 8992, 7, 763, 30], [8992, 7, 763, 30, 3816], [7, 763, 30, 3816, 55], [763, 30, 3816, 55, 67], [30, 3816, 55, 67, 502], [3816, 55, 67, 502, 24], [329, 224, 887, 871, 2106], [224, 887, 871, 2106, 7], [887, 871, 2106, 7, 1984], [871, 2106, 7, 1984, 332], [2106, 7, 1984, 332, 7], [7, 1984, 332, 7, 1772], [1984, 332, 7, 1772, 1059], [332, 7, 1772, 1059, 24], [329, 15, 238, 1939, 55], [15, 238, 1939, 55, 1404], [238, 1939, 55, 1404, 46], [1939, 55, 1404, 46, 169], [55, 1404, 46, 169, 201], [1404, 46, 169, 201, 55], [46, 169, 201, 55, 395], [169, 201, 55, 395, 872], [201, 55, 395, 872, 24], [123, 222, 410, 395, 112], [222, 410, 395, 112, 194], [410, 395, 112, 194, 294], [395, 112, 194, 294, 295], [112, 194, 294, 295, 24],

### Batch to Inputs and Targets

In [19]:
def process_batch(batch, window_size, vocab_len):
    
    batch_processed_X = []
    batch_processed_Y = []
    
    for window in batch:
        
        target_vector, context_vectors = generate_context_target(window, window_size, vocab_len)
        
        context_vector = average_context_vectors(context_vectors)
        
        batch_processed_X.append(context_vector)
        batch_processed_Y.append(target_vector)
    
    X = np.stack(batch_processed_X, axis = 1)
    X = X.reshape(X.shape[0],X.shape[1])
    Y = np.stack(batch_processed_Y, axis = 1)
    Y = Y.reshape(Y.shape[0],Y.shape[1])
    
    
    return X, Y
        
# TEST

X_test, Y_test = process_batch(Batches[1], window_size, len(vocab))
    
print(X_test)
print(X_test.shape)
print(Y_test.shape)
print(len(vocab))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(8995, 64)
(8995, 64)
8994


### Create the Model

In [24]:
def model(Batches, embedding_length, vocab_length, epochs, window_size, alpha=0.03, verbose = False):
    
    W1, W2, b1, b2 = initialize_model(embedding_length, vocab_length)
    counter = 0
    
    for i in range(epochs):
        for batch in Batches:
            batch_size = len(batch)
            
            X, Y = process_batch(batch, window_size, vocab_length)
            
            yhat, _, z1 = forward_prop(X, W1, W2, b1, b2)
            
            
            
            cost = compute_cost(Y, yhat, batch_size)
            
            grad_W1, grad_W2, grad_b1, grad_b2 = back_prop(X, yhat, Y, z1, W1, W2, b1, b2, batch_size)
        
            W1, W2, b1, b2 = update_parameters(W1, W2, b1, b2, grad_W1, grad_W2, grad_b1, grad_b2, alpha)
            
            if verbose:
                counter += 1
                if counter % 100 == 0:
                    print('Cost: {}'.format(cost))
                    print('\n')
                
        
    
    return W1, W2, b1, b2
        
    
    
    
    

In [25]:
model(Batches, 2, len(vocab), 1, 2, alpha=0.03, verbose = True)

Cost: 9.957950719426991


Cost: 10.015756214823623


Cost: 9.812436938953999


Cost: 9.860239085142986


Cost: 9.96493239739663


Cost: 9.93937079551459




KeyboardInterrupt: 